### ISSUE TITLE
Support for MacOS Sierra

### ISSUE THREAD

**Issue by RamonBeast** [subtitle-master/subtitlemaster#5]
SubtitleMaster doesn't seem to be compatible with MacOS Sierra, is a compatibility update planned? Thanks.

**Comment by wilkerlucio** [comment]
Hello @RamonBeast,

What version are you trying to run? I just downloaded the 2.0.1 from the releases (https://github.com/subtitle-master/subtitlemaster/releases), and it seems to be working fine.

If you are finding the signature error, please right click on the app and click to open (this will prompt you to open even though the software is not signed).

Please let me know how it goes there.

Thanks.

**Comment by RamonBeast** [comment]
My fault I wasn't running the latest version for some reasons, thanks!

**Comment by wilkerlucio** [comment]
I'm glad to hear :)
